[build]
  functions = "functions"
  command = "netlify-lambda install && mkdir ./public"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions."updateTimer"]
  schedule = "@hourly"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
